web/public/Assets/i18n/userProfile/en.json
web/src/Pages/UserProfile/UserProfile.tsx

own user profile deletion changes

own user profile deletion changes

---

backend/services/src/national-api/auth.controller.ts
web/public/Assets/i18n/common/en.json
web/src/Context/UserInformationContext/userInformationContext.tsx

Added error msg for session logout

Added error msg for session logout

---

web/src/Context/UserInformationContext/userInformationContext.tsx
web/src/Definitions/InterfacesAndType/userInformationContext.definitions.tsx
web/src/Pages/Login/login.scss
web/src/Pages/Login/login.tsx

Changes in session out info message

Changes in session out info message

---

backend/services/src/shared/user/user.service.ts

Removed the country validation in user adding service

Removed the country validation in user adding service

---

web/src/Pages/Company/addNewCompany.tsx

Fixed the issue in add new company logo validation msg issue

Fixed the issue in add new company logo validation msg issue

---

backend/services/src/i18n/en/user.json
web/public/Assets/i18n/forgotPassword/en.json
web/public/Assets/i18n/resetPassword/en.json
web/src/Pages/Login/forgotPassword.tsx
web/src/Pages/Login/login.scss
web/src/Pages/Login/resetPassword.tsx

Changes in forgot password UI and validation fixes

Changes in forgot password UI and validation fixes

---

backend/services/package.json
backend/services/src/shared/auth/auth.service.ts
backend/services/src/shared/email-helper/email-helper.service.ts
backend/services/src/shared/email-helper/email.template.ts
backend/services/src/shared/programme/programme.service.ts
backend/services/yarn.lock

Reverts xeptagondev/carbon-registry#17

Revert "fixed issues relate to emails"

---

backend/services/src/shared/user/user.service.ts
web/src/Context/UserInformationContext/userInformationContext.tsx
web/src/Pages/Login/login.tsx
web/src/Pages/Login/resetPassword.tsx

Carbon 132 changes

---

backend/services/src/shared/user/user.service.ts

Fixed the issue in user creation bcz of the incorrect condition check

Fixed the issue in user creation bcz of the incorrect condition check

---

backend/services/src/shared/util/validcountry.decorator.ts
backend/services/src/shared/validation/validation-exception.filter.ts

validation changes for user dto

validation changes for user dto

---

backend/services/src/analytics-api/aggregate.api.service.ts

Reverts xeptagondev/carbon-registry#38

Revert "Update aggregate.api.service.ts"

---

backend/services/src/shared/casl/casl-ability.factory.ts

Reverts xeptagondev/carbon-registry#47

Revert "refactor backend abilities"

---

backend/services/src/shared/programme/programme.service.ts

Added import for DataResponseMessageDto

Added import for DataResponseMessageDto

---

backend/services/src/shared/programme/programme.service.ts
web/src/App.tsx

Fixed the issue while rejecting already rejected programmes

Catbon 133 fixes

---

backend/services/src/shared/casl/casl.module.ts
backend/services/src/shared/casl/policy.guard.ts
backend/services/src/shared/user/user.service.ts

Changed the casl/ability default error message

Changed the casl/ability default error message

---

backend/services/src/i18n/en/user.json
backend/services/src/shared/dto/organisation.dto.ts
backend/services/src/shared/dto/user.dto.ts
backend/services/src/shared/user/user.service.ts
backend/services/src/shared/validation/validation-exception.filter.ts

- Changes in validation exception filter
- Changes in user service file regarding user on boarding success and error messages
- Changes in user on boarding response messages

Carbon 144

---

web/src/Components/Maps/MapboxComponent.tsx
web/src/Pages/Dashboard/dashboard.tsx

Added a limit for maxZoom for mapboxgl component

Added a limit for maxZoom for mapboxgl component

---

backend/services/src/shared/dto/organisation.dto.ts
backend/services/src/shared/dto/user.dto.ts
backend/services/src/shared/validation/validation-exception.filter.ts

Changes in organisation and user dtos

Changes in organisation and user dtos

---

backend/services/src/shared/user/user.service.ts
web/src/Pages/CompanyManagement/companyManagement.tsx

Added "-" for N/A values in organisations column for specified scenarios in the task

Added "-" for N/A values in organisations column

---

web/src/Context/ConnectionContext/connectionContext.tsx
web/src/Context/UserInformationContext/userInformationContext.tsx

Changes regarding expired token error message issue

CHanges regarding expired token error message issue

---

backend/services/src/shared/enum/sourceoffinding.enum.ts

Changes in sourceoffinding enums

Changes in sourceoffinding enums

---

web/src/Context/UserInformationContext/userInformationContext.tsx

Fixes for timeout error msg issue

Fixes for timeout error msg issue

---

backend/services/src/i18n/en/programme.json
backend/services/src/ledger-replicator/process.event.service.ts
backend/services/src/shared/entities/company.entity.ts
backend/services/src/shared/programme/programme.service.ts

Fixes for number of programme count issue for government root user

Fixes for number of programme count issue for government root user

---

backend/services/src/shared/auth/auth.module.ts
backend/services/src/shared/configuration.ts
docker-compose.yml

Added expiresIn to config file

Added expiresIn to config file

---

docker-compose-image.yml

changes in docker compose image file

changes in docker compose image file

---

backend/services/package.json
backend/services/src/shared/auth/auth.module.ts
backend/services/src/shared/configuration.ts
backend/services/yarn.lock
docker-compose-image.yml
docker-compose.yml

Updated server less offline lib

Updated serverless offline lib

---

web/src/Pages/Login/login.scss

FIxed the overlay issue

---

web/src/Pages/AddUser/addUser.tsx
web/src/Pages/Company/addNewCompany.tsx

Fixed optional phoneNo issue in company and user creation

Fixed optional phoneNo issue in company and user creation

---

web/src/Pages/Login/login.scss

Reverts xeptagondev/carbon-registry#127

Revert "FIxed the overlay issue"

---

web/package.json
web/yarn.lock

updated the carbon lib

---

web/src/Pages/ProgrammeView/programmeView.tsx

Fixed loc pin disappearing after programme view actions

Fixed loc pin disappearing after programme view actions

---

web/public/index.html

Changes regarding chat box in registry

CHanges regarding cht box in registry

---

backend/services/src/data-importer/importers/itmo-system.service.ts
backend/services/src/setup/handler.ts
backend/services/src/shared/casl/casl-ability.factory.ts
backend/services/src/shared/dto/organisation.dto.ts
backend/services/src/shared/entities/company.entity.ts
backend/services/src/shared/enum/company.role.enum.ts
backend/services/src/shared/programme/programme.service.ts
web/src/Casl/enums/company.role.enum.ts
web/src/Definitions/InterfacesAndType/programme.definitions.tsx
web/src/Pages/ProgrammeView/programmeView.tsx
web/yarn.lock

Ministry role changes

---

web/src/Pages/Dashboard/dashboard.tsx
web/src/Pages/ProgrammeManagement/programmeManagement.tsx

dashboard fixes for Ministry org
ministry level filer UI box fixes

Carbon 253

---

backend/services/src/setup/handler.ts
backend/services/src/shared/company/company.service.ts
backend/services/src/shared/user/user.service.ts
organisations.csv
users.csv

fixed ministry user creation from csv files

fixed ministry user creation from csv files

---

backend/services/src/shared/programme/programme.service.ts

retire programme min permission changes

Carbon 266 fixes

---

backend/services/src/shared/user/user.service.ts

Fixed min user creation issue

---

backend/services/src/shared/dto/filter.by.ts
backend/services/src/shared/dto/query.dto.ts
backend/services/src/shared/programme/programme.service.ts
web/src/Pages/Transfers/creditTransfers.tsx

programme transfer ministry level filter changes

programme transfer ministry level filter changes

---

web/src/Pages/Transfers/creditTransfer.scss
web/src/Pages/Transfers/creditTransfers.tsx

UI fixes in programme transfer table filter components

UI fixes in programme transfer table filter components

---

backend/services/src/shared/casl/casl-ability.factory.ts
web/src/Casl/ability.ts

permission changes for min users for viewing all users

permission changes for min users for viewing all users

---

backend/services/package.json
backend/services/src/async-operations-handler/handler.ts
backend/services/src/national-api/programme.controller.ts
backend/services/yarn.lock
docker-compose.yml

env variable change

---

backend/services/src/national-api/company.controller.ts
backend/services/src/national-api/user.controller.ts
backend/services/src/setup/handler.ts
web/public/Assets/i18n/addCompany/en.json
web/public/Assets/i18n/common/en.json
web/public/Assets/i18n/company/en.json
web/public/Assets/i18n/companyProfile/en.json
web/public/Assets/i18n/login/en.json
web/src/App.tsx
web/src/Casl/ability.ts
web/src/Pages/Company/registerNewCompany.tsx
web/src/Pages/CompanyManagement/companyManagement.tsx
web/src/Pages/Login/login.tsx

This change is not backward compatible. Requires the library changes to build.

NAM-1 NAM-2 adding company registration

---

.github/workflows/frontend-deployment-dev.yml
backend/services/package.json
backend/services/yarn.lock
web/package.json
web/src/Pages/ProgrammeView/programmeView.tsx
web/yarn.lock

deploy carbon-demo Programme view fix

---

backend/services/package.json
backend/services/yarn.lock
web/package.json
web/src/Pages/ProgrammeView/programmeView.tsx
web/yarn.lock

Missing language changes of OMGE in demo-carbReg system

Demo omge language fix

---

backend/services/package.json
backend/services/yarn.lock
web/package.json
web/public/index.html
web/yarn.lock

Deploy to demo

---

web/src/Pages/ProgrammeView/programmeView.tsx

fix for upcoming timeline

---

web/package.json
web/yarn.lock

Closing issues with this PR
CARBON-444

Carbon sprint 55

---

backend/services/package.json
backend/services/yarn.lock
web/package.json
web/src/Components/Sider/layout.sider.scss
web/src/Components/Sider/layout.sider.tsx
web/src/Pages/CompanyManagement/companyManagement.tsx
web/src/Pages/ProgrammeManagement/programmeManagement.tsx
web/yarn.lock

Issues closing with this change
- CARBON-469 - Front End Changes in the Unified System

Carbon sprint 58

---

backend/services/src/util/isNotPastDate.decorator.ts
web/src/Context/ConnectionContext/connectionContext.tsx

CARBON-505: Fixed start date and end date validation issue in project creation

---

web/src/Pages/Homepage/homepage.tsx

Doing this to trigger web pipeline in the demo

Homepage code refactor
